DwaPlanner:
  limits:
    max_velocity: [0.5, 2.0]
    max_acceleration: [2.0, 5.0]
    min_velocity: [0.0, -2.0]
    min_acceleration: [-2.0, -5.0]
  map_name_weight:
    - name: path
      value: 0.8
    - name: goal
      value: 0.9
    - name: obstacle
      value: 0.3
    - name: local_goal
      value: 0.3
  controller_dt: 0.1
  simulation_duration: 1.0
  num_vel_sample: 5
